language: node_js

node_js:
  - 0.8

before_script:
  - node test/runner.js
  - phantomjs --version
  - nohup python -m SimpleHTTPServer 8000 &

script: phantomjs tools/phantom.js http://127.0.0.1:8000/test/runner.html?console
